name : CI Coverage

on:
  push:
  pull_request:
    branches : [main]
    
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version:
          - "3.13.2"
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name : Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install pytest coverage
 
      - name: Run tests with coverage
        run: coverage run -m pytest test_fizzbuzz.py
 
      - name: Generate coverage report
        run: coverage report -m
