name: CI with Docker

on:
  push:
    branches: [main, docker]
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: New Docker image
        run: docker build -t app-fizzbuzz .

      - name: Run tests in Docker
        run : docker run app-fizzbuzz

